# Generated by Django 4.2.7 on 2023-11-28 15:41

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_movie_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=movie.models.upload_movie_image
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rate",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(blank=True),
        ),
    ]
