# Generated by Django 4.2.7 on 2023-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0003_alter_movie_image_alter_movie_rate_alter_movie_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
