# Generated by Django 4.2.7 on 2023-11-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0004_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="movie.category",
            ),
            preserve_default=False,
        ),
    ]
