# Generated by Django 4.2.7 on 2023-12-05 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0006_alter_movie_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rate",
            field=models.FloatField(
                blank=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
