# Generated by Django 4.2.7 on 2023-11-28 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("actor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actor",
            old_name="actor",
            new_name="movie",
        ),
    ]
