# Generated by Django 4.2.7 on 2023-12-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actor", "0003_alter_actor_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("femail", "FEMALE")],
                default="Male",
                max_length=8,
            ),
        ),
    ]
